# Generated by Django 4.2.3 on 2023-07-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_options_notes_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-pk'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
